# Generated by Django 4.2.16 on 2024-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_member_creation_date_alter_member_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
